name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          token: "${{ secrets.ADMIN_TOKEN }}"
      
      - uses: mbruno-kr/auto@patch-1
        with:
          token: "${{ secrets.ADMIN_TOKEN }}"