name: Release
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          token: "${{ secrets.ADMIN_TOKEN }}"
      
      - uses: mbround18/auto@pipeline-output
        id: auto
        with:
          token: "${{ secrets.ADMIN_TOKEN }}"
          
      - run: |
          # with out log
          echo "Output from Auto ${{ steps.auto.outputs.version }}"
